version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine

    container_name: 'rabbitmq'

    ports:
      - '15672:15672'

  service:
    build: .

    command: python amqp_service.py

    depends_on:
      - "rabbitmq"

  bot:
    build: .

    command: python bot.py

    depends_on:
      - "rabbitmq"